create sequence "public"."favoritos_id_favoritos_seq";

create sequence "public"."seguidores_id_seq";

create sequence "public"."usuarios_id_user_seq";

create table "public"."chat" (
    "id" uuid not null default gen_random_uuid(),
    "data_criacao" timestamp with time zone not null default now(),
    "nome" character varying,
    "isGrupo" boolean default false
);


create table "public"."chat_participantes" (
    "id" uuid not null default gen_random_uuid(),
    "chat_id" uuid not null,
    "id_user" text not null
);


create table "public"."comment_post" (
    "id" uuid not null default gen_random_uuid(),
    "content" text not null,
    "id_post" bigint,
    "autor_id" text
);


create table "public"."curtidas" (
    "id_curtida" uuid not null default uuid_generate_v4(),
    "id_post" bigint,
    "id_user" text
);


create table "public"."favoritos" (
    "id_favoritos" text not null,
    "id_user" text,
    "book_id" text
);


create table "public"."mensagens" (
    "id" uuid not null default gen_random_uuid(),
    "data_enviada" timestamp with time zone not null default now(),
    "chat_id" uuid not null,
    "user_id" text not null,
    "content" text not null,
    "visualizado" boolean not null default false
);


create table "public"."post" (
    "id" bigint generated by default as identity not null,
    "content" text not null,
    "book_id" text,
    "autor_id" text
);


create table "public"."recomendados" (
    "id_book" text not null
);


create table "public"."seguidores" (
    "id" integer not null default nextval('seguidores_id_seq'::regclass),
    "pessoa_seguidora_id" text not null,
    "pessoa_seguida_id" text not null,
    "data" timestamp without time zone default now()
);


create table "public"."usuarios" (
    "name" character varying(30),
    "id_user" text not null,
    "password" text,
    "email" character varying(255) not null,
    "username" text,
    "passou_introducao" boolean default false
);


alter sequence "public"."favoritos_id_favoritos_seq" owned by "public"."favoritos"."id_favoritos";

alter sequence "public"."seguidores_id_seq" owned by "public"."seguidores"."id";

alter sequence "public"."usuarios_id_user_seq" owned by "public"."usuarios"."id_user";

CREATE UNIQUE INDEX chat_participantes_pkey ON public.chat_participantes USING btree (id);

CREATE UNIQUE INDEX chat_pkey ON public.chat USING btree (id);

CREATE UNIQUE INDEX comment_post_pkey ON public.comment_post USING btree (id);

CREATE UNIQUE INDEX curtidas_pkey ON public.curtidas USING btree (id_curtida);

CREATE UNIQUE INDEX favoritos_pkey ON public.favoritos USING btree (id_favoritos);

CREATE UNIQUE INDEX mensagens_pkey ON public.mensagens USING btree (id);

CREATE UNIQUE INDEX post_pkey ON public.post USING btree (id);

CREATE UNIQUE INDEX recomendados_pkey ON public.recomendados USING btree (id_book);

CREATE UNIQUE INDEX seguidores_pessoa_seguidora_id_pessoa_seguida_id_key ON public.seguidores USING btree (pessoa_seguidora_id, pessoa_seguida_id);

CREATE UNIQUE INDEX seguidores_pkey ON public.seguidores USING btree (id);

CREATE UNIQUE INDEX usuarios_email_key ON public.usuarios USING btree (email);

CREATE UNIQUE INDEX usuarios_pkey ON public.usuarios USING btree (id_user);

CREATE UNIQUE INDEX usuarios_username_key ON public.usuarios USING btree (username);

alter table "public"."chat" add constraint "chat_pkey" PRIMARY KEY using index "chat_pkey";

alter table "public"."chat_participantes" add constraint "chat_participantes_pkey" PRIMARY KEY using index "chat_participantes_pkey";

alter table "public"."comment_post" add constraint "comment_post_pkey" PRIMARY KEY using index "comment_post_pkey";

alter table "public"."curtidas" add constraint "curtidas_pkey" PRIMARY KEY using index "curtidas_pkey";

alter table "public"."favoritos" add constraint "favoritos_pkey" PRIMARY KEY using index "favoritos_pkey";

alter table "public"."mensagens" add constraint "mensagens_pkey" PRIMARY KEY using index "mensagens_pkey";

alter table "public"."post" add constraint "post_pkey" PRIMARY KEY using index "post_pkey";

alter table "public"."recomendados" add constraint "recomendados_pkey" PRIMARY KEY using index "recomendados_pkey";

alter table "public"."seguidores" add constraint "seguidores_pkey" PRIMARY KEY using index "seguidores_pkey";

alter table "public"."usuarios" add constraint "usuarios_pkey" PRIMARY KEY using index "usuarios_pkey";

alter table "public"."chat_participantes" add constraint "chat_participantes_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES chat(id) not valid;

alter table "public"."chat_participantes" validate constraint "chat_participantes_chat_id_fkey";

alter table "public"."chat_participantes" add constraint "chat_participantes_id_user_fkey" FOREIGN KEY (id_user) REFERENCES usuarios(id_user) not valid;

alter table "public"."chat_participantes" validate constraint "chat_participantes_id_user_fkey";

alter table "public"."comment_post" add constraint "comment_post_autor_id_fkey" FOREIGN KEY (autor_id) REFERENCES usuarios(id_user) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_post" validate constraint "comment_post_autor_id_fkey";

alter table "public"."comment_post" add constraint "comment_post_id_post_fkey" FOREIGN KEY (id_post) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_post" validate constraint "comment_post_id_post_fkey";

alter table "public"."curtidas" add constraint "curtidas_id_post_fkey" FOREIGN KEY (id_post) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."curtidas" validate constraint "curtidas_id_post_fkey";

alter table "public"."curtidas" add constraint "curtidas_id_user_fkey" FOREIGN KEY (id_user) REFERENCES usuarios(id_user) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."curtidas" validate constraint "curtidas_id_user_fkey";

alter table "public"."favoritos" add constraint "favoritos_id_user_fkey" FOREIGN KEY (id_user) REFERENCES usuarios(id_user) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favoritos" validate constraint "favoritos_id_user_fkey";

alter table "public"."mensagens" add constraint "mensagens_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES chat(id) not valid;

alter table "public"."mensagens" validate constraint "mensagens_chat_id_fkey";

alter table "public"."mensagens" add constraint "mensagens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES usuarios(id_user) not valid;

alter table "public"."mensagens" validate constraint "mensagens_user_id_fkey";

alter table "public"."post" add constraint "post_autor_id_fkey" FOREIGN KEY (autor_id) REFERENCES usuarios(id_user) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post" validate constraint "post_autor_id_fkey";

alter table "public"."seguidores" add constraint "seguidores_pessoa_seguida_id_fkey" FOREIGN KEY (pessoa_seguida_id) REFERENCES usuarios(id_user) ON DELETE CASCADE not valid;

alter table "public"."seguidores" validate constraint "seguidores_pessoa_seguida_id_fkey";

alter table "public"."seguidores" add constraint "seguidores_pessoa_seguidora_id_fkey" FOREIGN KEY (pessoa_seguidora_id) REFERENCES usuarios(id_user) ON DELETE CASCADE not valid;

alter table "public"."seguidores" validate constraint "seguidores_pessoa_seguidora_id_fkey";

alter table "public"."seguidores" add constraint "seguidores_pessoa_seguidora_id_pessoa_seguida_id_key" UNIQUE using index "seguidores_pessoa_seguidora_id_pessoa_seguida_id_key";

alter table "public"."usuarios" add constraint "usuarios_email_key" UNIQUE using index "usuarios_email_key";

alter table "public"."usuarios" add constraint "usuarios_username_key" UNIQUE using index "usuarios_username_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.fetch_posts_with_counts()
 RETURNS TABLE(id uuid, title text, content text, curtidas integer, comentarios integer)
 LANGUAGE plpgsql
AS $function$
begin
  return query
  select 
    p.id, 
    p.title, 
    p.content, 
    co.curtidas, 
    cm.comentarios
  from post p
  inner join (
    select id_post, count(*) as curtidas
    from curtidas
    group by id_post
  ) co on co.id_post = p.id
  inner join (
    select id_post, count(*) as comentarios
    from comment_post
    group by id_post
  ) cm on cm.id_post = p.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_seguidores(user_id text)
 RETURNS TABLE(id_user text, name character varying, username text)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT u.id_user, u.name, u.username
  FROM usuarios u
  JOIN seguidores s ON u.id_user = s.pessoa_seguidora_id
  WHERE s.pessoa_seguida_id = user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_seguindo(user_id text)
 RETURNS TABLE(id_user text, name character varying, username text)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT u.id_user, u.name, u.username
  FROM usuarios u
  JOIN seguidores s ON u.id_user = s.pessoa_seguida_id
  WHERE s.pessoa_seguidora_id = user_id;
END;
$function$
;

create or replace view "public"."list_chats_view" as  SELECT p.chat_id,
    c.data_criacao,
    u.name,
    u.username,
    u.id_user,
    m.content,
    m.visualizado,
    m.user_id AS id_do_usuario_que_enviou_ultima_msg
   FROM (((chat_participantes p
     JOIN chat c ON (((p.chat_id = c.id) AND (c."isGrupo" = false))))
     JOIN usuarios u ON ((p.id_user = u.id_user)))
     JOIN mensagens m ON ((m.chat_id = c.id)))
  ORDER BY m.data_enviada DESC;


create or replace view "public"."postagens" as  SELECT p.id,
    p.content,
    p.book_id,
    p.autor_id,
    co.curtidas,
    cm.comentarios
   FROM ((post p
     LEFT JOIN ( SELECT curtidas.id_post,
            count(*) AS curtidas
           FROM curtidas
          GROUP BY curtidas.id_post) co ON ((co.id_post = p.id)))
     LEFT JOIN ( SELECT comment_post.id_post,
            count(*) AS comentarios
           FROM comment_post
          GROUP BY comment_post.id_post) cm ON ((cm.id_post = p.id)));


create or replace view "public"."seguidores_view" as  SELECT u.name,
    u.id_user,
    u.password,
    u.email,
    u.username,
    u.passou_introducao
   FROM (usuarios u
     JOIN seguidores s ON ((u.id_user = s.pessoa_seguidora_id)))
  WHERE (s.pessoa_seguida_id = 'user_id'::text);


grant delete on table "public"."chat" to "anon";

grant insert on table "public"."chat" to "anon";

grant references on table "public"."chat" to "anon";

grant select on table "public"."chat" to "anon";

grant trigger on table "public"."chat" to "anon";

grant truncate on table "public"."chat" to "anon";

grant update on table "public"."chat" to "anon";

grant delete on table "public"."chat" to "authenticated";

grant insert on table "public"."chat" to "authenticated";

grant references on table "public"."chat" to "authenticated";

grant select on table "public"."chat" to "authenticated";

grant trigger on table "public"."chat" to "authenticated";

grant truncate on table "public"."chat" to "authenticated";

grant update on table "public"."chat" to "authenticated";

grant delete on table "public"."chat" to "service_role";

grant insert on table "public"."chat" to "service_role";

grant references on table "public"."chat" to "service_role";

grant select on table "public"."chat" to "service_role";

grant trigger on table "public"."chat" to "service_role";

grant truncate on table "public"."chat" to "service_role";

grant update on table "public"."chat" to "service_role";

grant delete on table "public"."chat_participantes" to "anon";

grant insert on table "public"."chat_participantes" to "anon";

grant references on table "public"."chat_participantes" to "anon";

grant select on table "public"."chat_participantes" to "anon";

grant trigger on table "public"."chat_participantes" to "anon";

grant truncate on table "public"."chat_participantes" to "anon";

grant update on table "public"."chat_participantes" to "anon";

grant delete on table "public"."chat_participantes" to "authenticated";

grant insert on table "public"."chat_participantes" to "authenticated";

grant references on table "public"."chat_participantes" to "authenticated";

grant select on table "public"."chat_participantes" to "authenticated";

grant trigger on table "public"."chat_participantes" to "authenticated";

grant truncate on table "public"."chat_participantes" to "authenticated";

grant update on table "public"."chat_participantes" to "authenticated";

grant delete on table "public"."chat_participantes" to "service_role";

grant insert on table "public"."chat_participantes" to "service_role";

grant references on table "public"."chat_participantes" to "service_role";

grant select on table "public"."chat_participantes" to "service_role";

grant trigger on table "public"."chat_participantes" to "service_role";

grant truncate on table "public"."chat_participantes" to "service_role";

grant update on table "public"."chat_participantes" to "service_role";

grant delete on table "public"."comment_post" to "anon";

grant insert on table "public"."comment_post" to "anon";

grant references on table "public"."comment_post" to "anon";

grant select on table "public"."comment_post" to "anon";

grant trigger on table "public"."comment_post" to "anon";

grant truncate on table "public"."comment_post" to "anon";

grant update on table "public"."comment_post" to "anon";

grant delete on table "public"."comment_post" to "authenticated";

grant insert on table "public"."comment_post" to "authenticated";

grant references on table "public"."comment_post" to "authenticated";

grant select on table "public"."comment_post" to "authenticated";

grant trigger on table "public"."comment_post" to "authenticated";

grant truncate on table "public"."comment_post" to "authenticated";

grant update on table "public"."comment_post" to "authenticated";

grant delete on table "public"."comment_post" to "service_role";

grant insert on table "public"."comment_post" to "service_role";

grant references on table "public"."comment_post" to "service_role";

grant select on table "public"."comment_post" to "service_role";

grant trigger on table "public"."comment_post" to "service_role";

grant truncate on table "public"."comment_post" to "service_role";

grant update on table "public"."comment_post" to "service_role";

grant delete on table "public"."curtidas" to "anon";

grant insert on table "public"."curtidas" to "anon";

grant references on table "public"."curtidas" to "anon";

grant select on table "public"."curtidas" to "anon";

grant trigger on table "public"."curtidas" to "anon";

grant truncate on table "public"."curtidas" to "anon";

grant update on table "public"."curtidas" to "anon";

grant delete on table "public"."curtidas" to "authenticated";

grant insert on table "public"."curtidas" to "authenticated";

grant references on table "public"."curtidas" to "authenticated";

grant select on table "public"."curtidas" to "authenticated";

grant trigger on table "public"."curtidas" to "authenticated";

grant truncate on table "public"."curtidas" to "authenticated";

grant update on table "public"."curtidas" to "authenticated";

grant delete on table "public"."curtidas" to "service_role";

grant insert on table "public"."curtidas" to "service_role";

grant references on table "public"."curtidas" to "service_role";

grant select on table "public"."curtidas" to "service_role";

grant trigger on table "public"."curtidas" to "service_role";

grant truncate on table "public"."curtidas" to "service_role";

grant update on table "public"."curtidas" to "service_role";

grant delete on table "public"."favoritos" to "anon";

grant insert on table "public"."favoritos" to "anon";

grant references on table "public"."favoritos" to "anon";

grant select on table "public"."favoritos" to "anon";

grant trigger on table "public"."favoritos" to "anon";

grant truncate on table "public"."favoritos" to "anon";

grant update on table "public"."favoritos" to "anon";

grant delete on table "public"."favoritos" to "authenticated";

grant insert on table "public"."favoritos" to "authenticated";

grant references on table "public"."favoritos" to "authenticated";

grant select on table "public"."favoritos" to "authenticated";

grant trigger on table "public"."favoritos" to "authenticated";

grant truncate on table "public"."favoritos" to "authenticated";

grant update on table "public"."favoritos" to "authenticated";

grant delete on table "public"."favoritos" to "service_role";

grant insert on table "public"."favoritos" to "service_role";

grant references on table "public"."favoritos" to "service_role";

grant select on table "public"."favoritos" to "service_role";

grant trigger on table "public"."favoritos" to "service_role";

grant truncate on table "public"."favoritos" to "service_role";

grant update on table "public"."favoritos" to "service_role";

grant delete on table "public"."mensagens" to "anon";

grant insert on table "public"."mensagens" to "anon";

grant references on table "public"."mensagens" to "anon";

grant select on table "public"."mensagens" to "anon";

grant trigger on table "public"."mensagens" to "anon";

grant truncate on table "public"."mensagens" to "anon";

grant update on table "public"."mensagens" to "anon";

grant delete on table "public"."mensagens" to "authenticated";

grant insert on table "public"."mensagens" to "authenticated";

grant references on table "public"."mensagens" to "authenticated";

grant select on table "public"."mensagens" to "authenticated";

grant trigger on table "public"."mensagens" to "authenticated";

grant truncate on table "public"."mensagens" to "authenticated";

grant update on table "public"."mensagens" to "authenticated";

grant delete on table "public"."mensagens" to "service_role";

grant insert on table "public"."mensagens" to "service_role";

grant references on table "public"."mensagens" to "service_role";

grant select on table "public"."mensagens" to "service_role";

grant trigger on table "public"."mensagens" to "service_role";

grant truncate on table "public"."mensagens" to "service_role";

grant update on table "public"."mensagens" to "service_role";

grant delete on table "public"."post" to "anon";

grant insert on table "public"."post" to "anon";

grant references on table "public"."post" to "anon";

grant select on table "public"."post" to "anon";

grant trigger on table "public"."post" to "anon";

grant truncate on table "public"."post" to "anon";

grant update on table "public"."post" to "anon";

grant delete on table "public"."post" to "authenticated";

grant insert on table "public"."post" to "authenticated";

grant references on table "public"."post" to "authenticated";

grant select on table "public"."post" to "authenticated";

grant trigger on table "public"."post" to "authenticated";

grant truncate on table "public"."post" to "authenticated";

grant update on table "public"."post" to "authenticated";

grant delete on table "public"."post" to "service_role";

grant insert on table "public"."post" to "service_role";

grant references on table "public"."post" to "service_role";

grant select on table "public"."post" to "service_role";

grant trigger on table "public"."post" to "service_role";

grant truncate on table "public"."post" to "service_role";

grant update on table "public"."post" to "service_role";

grant delete on table "public"."recomendados" to "anon";

grant insert on table "public"."recomendados" to "anon";

grant references on table "public"."recomendados" to "anon";

grant select on table "public"."recomendados" to "anon";

grant trigger on table "public"."recomendados" to "anon";

grant truncate on table "public"."recomendados" to "anon";

grant update on table "public"."recomendados" to "anon";

grant delete on table "public"."recomendados" to "authenticated";

grant insert on table "public"."recomendados" to "authenticated";

grant references on table "public"."recomendados" to "authenticated";

grant select on table "public"."recomendados" to "authenticated";

grant trigger on table "public"."recomendados" to "authenticated";

grant truncate on table "public"."recomendados" to "authenticated";

grant update on table "public"."recomendados" to "authenticated";

grant delete on table "public"."recomendados" to "service_role";

grant insert on table "public"."recomendados" to "service_role";

grant references on table "public"."recomendados" to "service_role";

grant select on table "public"."recomendados" to "service_role";

grant trigger on table "public"."recomendados" to "service_role";

grant truncate on table "public"."recomendados" to "service_role";

grant update on table "public"."recomendados" to "service_role";

grant delete on table "public"."seguidores" to "anon";

grant insert on table "public"."seguidores" to "anon";

grant references on table "public"."seguidores" to "anon";

grant select on table "public"."seguidores" to "anon";

grant trigger on table "public"."seguidores" to "anon";

grant truncate on table "public"."seguidores" to "anon";

grant update on table "public"."seguidores" to "anon";

grant delete on table "public"."seguidores" to "authenticated";

grant insert on table "public"."seguidores" to "authenticated";

grant references on table "public"."seguidores" to "authenticated";

grant select on table "public"."seguidores" to "authenticated";

grant trigger on table "public"."seguidores" to "authenticated";

grant truncate on table "public"."seguidores" to "authenticated";

grant update on table "public"."seguidores" to "authenticated";

grant delete on table "public"."seguidores" to "service_role";

grant insert on table "public"."seguidores" to "service_role";

grant references on table "public"."seguidores" to "service_role";

grant select on table "public"."seguidores" to "service_role";

grant trigger on table "public"."seguidores" to "service_role";

grant truncate on table "public"."seguidores" to "service_role";

grant update on table "public"."seguidores" to "service_role";

grant delete on table "public"."usuarios" to "anon";

grant insert on table "public"."usuarios" to "anon";

grant references on table "public"."usuarios" to "anon";

grant select on table "public"."usuarios" to "anon";

grant trigger on table "public"."usuarios" to "anon";

grant truncate on table "public"."usuarios" to "anon";

grant update on table "public"."usuarios" to "anon";

grant delete on table "public"."usuarios" to "authenticated";

grant insert on table "public"."usuarios" to "authenticated";

grant references on table "public"."usuarios" to "authenticated";

grant select on table "public"."usuarios" to "authenticated";

grant trigger on table "public"."usuarios" to "authenticated";

grant truncate on table "public"."usuarios" to "authenticated";

grant update on table "public"."usuarios" to "authenticated";

grant delete on table "public"."usuarios" to "service_role";

grant insert on table "public"."usuarios" to "service_role";

grant references on table "public"."usuarios" to "service_role";

grant select on table "public"."usuarios" to "service_role";

grant trigger on table "public"."usuarios" to "service_role";

grant truncate on table "public"."usuarios" to "service_role";

grant update on table "public"."usuarios" to "service_role";

create policy "Favoritos só podem ser acessados se estiver Autenticado"
on "public"."favoritos"
as permissive
for select
to authenticated
using (true);



